### ISSUE TITLE
[Bug Report] No module named 'rl_sdk'

### ISSUE THREAD

**Issue by jingdaliang** [fan-ziqi/rl_sar#30]
source devel/setup.bash
(for python version) rosrun rl_sar rl_sim.py
在执行这一步的时候报错：Traceback (most recent call last):
  File "/home/robot/lite2/devel/lib/rl_sar/rl_sim.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/robot/lite2/src/rl_sar/src/rl_sar/scripts/rl_sim.py", line 17, in <module>
    from rl_sdk import *
ModuleNotFoundError: No module named 'rl_sdk'
如图
![8EF338669ACE22A7BA40173138B7213B](https://github.com/user-attachments/assets/2366c4a1-0afe-4772-aec6-1b6035e2647c)
报错的位置如图
![0F581D51340DEBB2B51510C75A9FA8D6](https://github.com/user-attachments/assets/17daaacd-6216-49fc-b33c-e99aa3828381)
![96C8E2897D1F29DDB52A370D2E4154C5](https://github.com/user-attachments/assets/777760e3-58a4-43d3-b862-0b4673aca46a)

麻烦大佬解答

**Comment by fan-ziqi** [comment]
我这边无法复现您的问题。

请根据下述模板详细说明你的软件版本以及你都做了什么操作，你都用了模板为什么要把下面的内容删掉呢？这对我帮你找到问题很有帮助。请直接修改你上面的内容，无需重新开一个新帖。

If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

A clear and concise description of what the bug is.

### Steps to reproduce

Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.



### System Info

Describe the characteristic of your environment:


- Commit: [e.g. 8f3b9ca]
- OS: [e.g. Ubuntu 20.04, Ubuntu 22.04, WSL2]
- ROS Version: [e.g. noetic, melodic]
- Python Version: [e.g. Python 3.8, Conda-Python 3.11]

### Additional context

Add any other context about the problem here.

### Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by jingdaliang** [comment]
解决啦，麻烦了，顺便问一下这个框架可以换任何四足机器人模型吗

**Comment by fan-ziqi** [comment]
可以，任何机器人都可以

**Comment by fan-ziqi** [comment]
请问你是如何解决的？可以给其他人一个参考吗

**Comment by jingdaliang** [comment]
就是路径问题，我本来是自己建了一个src把 rl_sar 放在里边，然后build的，现在直接在rl_sar这个根目录下build的，一开始理解错了，哈哈哈哈，麻烦大佬了
