### ISSUE TITLE
How to choose data for Cyberdog training?

### ISSUE THREAD

**Issue by RubSevian** [fan-ziqi/rl_sar#4]
I want to repeat your success and possibly improve walking, and for this I really need information about where you conducted and what you based your Cyberdog training on.Please

**Comment by fan-ziqi** [comment]
I use [legged_gym](https://github.com/leggedrobotics/legged_gym) as the base framework, and the model is based on a modified version of cyberdog1_description with parameters provided by the official repository [cyberdog1_description](https://github.com/fan-ziqi/cyberdog1_description). The environment setup uses the script [rl_docker](https://github.com/fan-ziqi/rl_docker).

However, after testing, it was found that using Kp=20 and Kd=0.5 does not enable walking on the real dog. Therefore, it is recommended to use the actuator_network instead of PD for training.

**Comment by RubSevian** [comment]
Hello, I have assembled your rl_docker.I would like to learn more about the Cyberdog robot training process, can you tell me more about it?

**Comment by fan-ziqi** [comment]
Please join Discord group in rl_sar README
